name: Deploy to EC2

# Trigger this workflow on push to the main branch or when the "Build and Push Docker Images" workflow completes
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the SSH private key for secure access to the EC2 instance
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the SSH private key stored in GitHub Secrets
          known_hosts: "13.50.65.12" # Specify the known host to avoid SSH verification prompts

      # Connect to the EC2 instance and run the deployment script
      - name: Deploy to EC2
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          PREVIOUS_TAG=previous  
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-50-65-12.eu-north-1.compute.amazonaws.com "bash /home/ubuntu/deployRestart.sh $IMAGE_TAG $PREVIOUS_TAG"

      # Connect to the EC2 instance and execute the deploy.sh script located at /home/ubuntu

      # The -o StrictHostKeyChecking=no option prevents SSH from prompting to confirm the host's fingerprint
